name: GitHub Actions Demo
run-name: Tests before push
on: [push]
jobs:
  front_end_tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Github action event : ${{ github.event_name }}."
      - run: echo "🔎 Branc name is ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v4
